apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8005
  selector:
    app: analytics-service