
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secret
  namespace: togglemaster
type: Opaque

stringData:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: COLOQUE A SUA FILA SQS
  AWS_DYNAMODB_TABLE: COLOQUE O SEU DB DYNAMO

