apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: INFORME O ENDPOINT DO DB
  AUTH_SERVICE_URL: INFORME A URL DO AUTH-SERVICE
