apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  # Redis
  REDIS_URL: INFORME O URL REDIS

  # Banco PostgreSQL
  DATABASE_URL:  INFORME O ENDPOINT DO DB

   # AWS (credenciais virão da IAM Role do Node)
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: INFORME A FILA SQS
  AWS_DYNAMODB_TABLE: INFORME O NOME DA TABELA DO DYNAMO

  # Endpoints internos dos serviços
  AUTH_SERVICE_URL: URL LB DO SERVICE
  FLAG_SERVICE_URL: URL DO FLAG SERVICE
  TARGETING_SERVICE_URL: URL DO TARGETING SERVICE

