apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secret
  namespace: togglemaster
type: Opaque

stringData:
  # Banco PostgreSQL
  DATABASE_URL: "postgresql://targetinguser:TargetingPass123!@targeting-postgres.cpfuspfkkck3.us-east-1.rds.amazonaws.com:5432/targetingdb"

  # Endpoint interno do Auth
  AUTH_SERVICE_URL: "http://auth-service.togglemaster.svc.cluster.local:8001"

  # AWS (credenciais via IAM Role do Node)
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/397233770793/evaluation-analytics-queue"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
